// flow-typed signature: 71a7ad5e6beab3faed5f168c4e2d2e8b
// flow-typed version: <<STUB>>/lockr_v0.8.*/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lockr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lockr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lockr/lockr' {
  declare module.exports: any;
}

declare module 'lockr/lockr.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lockr/lockr.js' {
  declare module.exports: $Exports<'lockr/lockr'>;
}
declare module 'lockr/lockr.min.js' {
  declare module.exports: $Exports<'lockr/lockr.min'>;
}
